package grep.neogulcoder.domain.alram.type;

public enum AlarmType {
    STUDY_INVITE,
    STUDY_EXTEND,
    STUDY_EXTENSION_REMINDER,
    STUDY_POST_COMMENT,
    TIME_VOTE_REQUEST,
    STUDY_APPLICATION,
    STUDY_APPLICATION_APPROVED,
    STUDY_APPLICATION_REJECTED,
    RECRUITMENT_POST_COMMENT
}
